### ISSUE TITLE
Can you describe the specific use of upgmpp? especially the combination of ontology and CRF?

### ISSUE THREAD

**Issue by wxj183** [jotaraul/upgmpp#5]

**Comment by jotaraul** [comment]
Hi,

UPGMpp is a software library written in C++ for the building, training, and managing of Undirected Probabilistic Graphical Models in C++, including CRFs.

In my personal experience, I've used it in algong with ontologies for training CRFs for recognizing objects and rooms with synthetic data, for improving the recognition results by contrasting them with the ontology, and for learning from experience. More information about this can be found in my publications and PhD thesis [here](https://www.researchgate.net/profile/Jr_Ruiz-Sarmiento/contributions).

Hope that helps.
